### PR TITLE
Briandev

### PR DESCRIPTION
**Pull request by dongkatsu**
Older displays (cargo, gold, colony trading) all working as intended alongside new EU price message implementations.

### CODE REVIEW

**Comment by MikeJeffers** [comment]
Brain, the commits for your experiments with 199 need to be removed from this pull.  Consider creating a separate branch, reverting these changes, and only adding the fixes.  They are in separate classes/files so that makes things clear.  

After which, if we can verify 43 is done.  We will branch that off onto a stable release branch.  Clone that into a fork of SourceForge FreeCol repo, and do the merge request for 43

**Comment by dongkatsu** [comment]
#199 removed

**Comment by seongminp** [comment]
Shouldn't 

- 1f6f027: Fixed logical order of SHIFT+CONTROL check 
- 73c3b82: Added new SHIFT+CONTROL state in listeners

Also be removed?

**Comment by dongkatsu** [comment]
@seongminnpark If you look in files changed, those were removed so I think it's resolved

**Pull request merged**
